#!/bin/bash
#
# Converte arquivos de latin-1 para UTF-8.
# Passe os arquivos desejados na linha comando, exemplo:
#
#    ./utf8 02-qualidade/*
#

for arquivo
do
	cp "$arquivo" .tmp &&
	iconv -f latin1 -t UTF-8 .tmp > "$arquivo" &&
	echo "Convertido para UTF-8: $arquivo"
done
rm -f .tmp
